### ISSUE TITLE
Brisanje vrednosti

### ISSUE THREAD

**Issue by avojvodic992** [ivanstan/yahtzee#6]
Kad se klikne na celiju, omoguciti brisanje i na backspase a ne samo na delete. 

(sta mislis da li da se brise stara vrednost ako krenes da kucas novu? Da ne mora da se brise uopste nego da se automatski popunjava)

**Comment by ivanstan** [comment]
Ne znam bas kako je ovaj predlog ostvariv!? Sta ako se kuca dvocifrenu broj kako cu znati da li je korisnik poceo da kuca ili je ukucao drugu cifru broja? Ono sto bih sigurno mogao je da na click obrisem vrednost koja postoji, kako ti se to cini?

**Comment by avojvodic992** [comment]
Onda ne mora i ovako je ok :)
